---

- name: Make sure FirewallD is started
  service:
    name: firewalld
    state: started

- name: Open HTTP Firewalld ports
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Open HTTPS Firewalld ports
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Provide NGINX with new configuration
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644

- name: Create NGINX log path
  file:
    path: '{{ nginx_access_log_path }}'
    state: directory

- name: Create NGINX log file
  file:
    path: '{{ nginx_access_log_path }}{{ nginx_access_log_file }}'
    state: touch

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
